#!/usr/bin/env python
import importlib
import rostest
import sys
import unittest


class TestVirtualenv(unittest.TestCase):

    def test_import_wrapt(self):
        importlib.import_module("wrapt")


if __name__ == '__main__':
    rostest.rosrun('test_catkin_virtualenv', 'test_virtualenv_script', TestVirtualenv, sys.argv)
