#!/usr/bin/env python3
# Software License Agreement (GPL)
#
# \file      venv_install
# \authors   Paul Bovbel <pbovbel@locusrobotics.com>
# \copyright Copyright (c) (2017,), Locus Robotics, All rights reserved.
#
# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

import argparse
import typing

from catkin_virtualenv import configure_logging
from catkin_virtualenv.cli import _parse_install_args, _build_sanitized_extra_args
from catkin_virtualenv.venv import Virtualenv
from catkin_virtualenv.uvvenv import UVVirtualEnv, UvPackageInstallation


def main(argv: typing.Union[typing.List[str], None] = None) -> None:
    configure_logging()
    args = _parse_install_args(argv)

    if not args.use_uv:
        sanitized_extra_pip_args = _build_sanitized_extra_args(args, use_uv=False)
        venv = Virtualenv(args.venv)
        venv.install(
            requirements=args.requirements,
            extra_pip_args=sanitized_extra_pip_args,
        )
    else:
        sanitized_extra_uv_args = _build_sanitized_extra_args(args, use_uv=True)
        uvvenv = UVVirtualEnv(args.venv, cache_dir=args.uv_cache)
        uvvenv.install(UvPackageInstallation(args.requirements, extra_uv_args=sanitized_extra_uv_args))


if __name__ == "__main__":
    main()
